name: Step 0, Start the course

# This step triggers after the learner creates a new repository from the template.
# This workflow updates from step 0 to step 1.

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  get_current_step:
    name: Check current step
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_repo_created:
    name: Proceed to Step 1
    needs: get_current_step
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 0 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Checkout all branches

      - name: Prepare a branch and update repository
        run: |
          echo "Ensure we are on step 0"
          if [ "$(cat .github/steps/-step.txt)" != 0 ]
          then
            echo "Current step is not 0"
            exit 0
          fi

          echo "Create a new branch"
          BRANCH=update-step-1
          git checkout -b $BRANCH

          echo "Make an update to README"
          sed -i.bak 's/Welcome to Step 0!/Welcome to Step 1!/' README.md

          echo "Commit changes"
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add README.md
          git commit --message="Update to Step 1"

          echo "Push changes"
          git push --set-upstream origin $BRANCH

          echo "Switch back to main branch"
          git checkout main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update to Step 1
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 0
          to_step: 1
          branch_name: update-step-1
